#!/usr/bin/bash
current_vol_percent=`amixer | awk '/Front Left: Playback/ {gsub(/[\[\]]/,"",$5); print $5}'`
current_vol_number=`amixer | awk '/Front Left: Playback/ {gsub(/[\[\]]/,"",$5); print $5}' | cut -d '%' -f 1`
icon="\uf028"

# Change icon if < 50%
if [[ $current_vol_number -lt 50 ]]; then
  icon="\uf027"
fi

# Change icon if silent
if amixer get Master | grep -q off; then
    icon="\uf026"
fi

echo -e $icon" "$current_vol_percent
