#! /bin/bash

echo "loading bar";
source $(dirname $0)/config

num_mon=$(bspc query -M | wc -l)
PADDING="  "

while read -r line ; do
    case $line in
        B*)
            # battery output
            battery="$PADDING${line#?}$PADDING"
            ;;
        C*)
            # clock output
            clock="$PADDING${line#?}$PADDING"
            ;;
        L*)
            # wifi output
            wifi="$PADDING${line#?}$PADDING"
            ;;
        V*)
            # volume output
            volume="$PADDING${line#?}$PADDING"
            ;;
        T*)
            # window title
            title="$PADDING$PADDING${line#?}$PADDING$PADDING"
            ;;
        W*)
            # bspwm internal state
            wm=""
            IFS=':'
            set -- ${line#?}
            while [ $# -gt 0 ] ; do
                item=$1
                name=${item#?}
                case $item in
                    [fFoOuU]*)
                        case $item in
                            f*)
                                # free desktop
                                FG=$COLOR_FREE_FG
                                BG=$COLOR_FREE_BG
                                ;;
                            F*)
                                # focused free desktop
                                FG=$COLOR_FOCUSED_FREE_FG
                                BG=$COLOR_FOCUSED_FREE_BG
                                ;;
                            o*)
                                # occupied desktop
                                FG=$COLOR_OCCUPIED_FG
                                BG=$COLOR_OCCUPIED_BG
                                ;;
                            O*)
                                # focused occupied desktop
                                FG=$COLOR_FOCUSED_OCCUPIED_FG
                                BG=$COLOR_FOCUSED_OCCUPIED_BG
                                ;;
                            u*)
                                # urgent desktop
                                FG=$COLOR_URGENT_FG
                                BG=$COLOR_URGENT_BG
                                ;;
                            U*)
                                # focused urgent desktop
                                FG=$COLOR_FOCUSED_URGENT_FG
                                BG=$COLOR_FOCUSED_URGENT_BG
                                ;;
                        esac
                        wm="${wm}%{F${FG}}%{B${BG}}%{U$COLOR_FOREGROUND}%{A:bspc desktop -f ${name}:}$PADDING${name}$PADDING%{A}%{B-}%{F-}"
                        ;;
                esac
                shift
            done
            ;;
    esac
    printf "%s\n" "%{1}$wm %{c}${title} %{r}${wifi}${volume}${battery}${clock}"
done

