#! /usr/bin/sh

cd $(dirname $0)
source $(dirname $0)/config

if [ $(pgrep -cx panel) -gt 1 ] ; then
	printf "%s\n" "The panel is already running." >&2
	exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

bspc config top_padding $PANEL_HEIGHT


bspc control --subscribe > "$PANEL_FIFO" &
xtitle -sf 'T%s' > "$PANEL_FIFO" &


while true ; do
	WIFI=$(~/.config/bspwm/panel/scripts/wireless)
	VOLUME=$(~/.config/bspwm/panel/scripts/volume)
	CLOCK=$(~/.config/bspwm/panel/scripts/clock)
	RAM=$(~/.config/bspwm/panel/scripts/ram)
	BATTERIES=$(~/.config/bspwm/panel/scripts/batteries)

	echo "S" $WIFI "|" $RAM%% "|" $BATTERIES "|" $VOLUME%%  "|" $CLOCK " " > "$PANEL_FIFO" &
	sleep 5s
done &

cat $PANEL_FIFO \
	| $(dirname $0)/panel_bar \
	| bar \
		-g 1920x$PANEL_HEIGHT \
		-B $COLOR_BACKGROUND \
		-F $COLOR_FOREGROUND \
		-f $FONT &

wait
