#! /usr/bin/sh

cd $(dirname $0)
source $(dirname $0)/config

if [ $(pgrep -cx panel) -gt 1 ] ; then
	printf "%s\n" "The panel is already running." >&2
	exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

bspc config top_padding $PANEL_HEIGHT
bspc subscribe report > "$PANEL_FIFO" &
xtitle -sf 'T%s' > "$PANEL_FIFO" &

while true; do
	batteries=$(~/.config/bspwm/panel/scripts/batteries)
	echo "B${batteries}";
	sleep 30;
done > $PANEL_FIFO &

while true; do
	clock=$(~/.config/bspwm/panel/scripts/clock)
	echo "C${clock}";
	sleep 60;
done > $PANEL_FIFO &

while true; do
	wifi=$(~/.config/bspwm/panel/scripts/wireless)
	echo "L${wifi}";
	sleep 10;
done > $PANEL_FIFO &

while true; do
	volume=$(~/.config/bspwm/panel/scripts/volume)
	echo "V${volume}";
	sleep 1;
done > $PANEL_FIFO &

cat $PANEL_FIFO \
	| $(dirname $0)/panel_bar  \
	| lemonbar \
		-g x$PANEL_HEIGHT \
		-B $COLOR_BACKGROUND \
		-F $COLOR_FOREGROUND \
		-f $ICON_FONT \
		-f $FONT &

wait
