#! /usr/bin/sh

curdir=$(dirname $0)
cd $curdir
source $curdir/config

panel_dir=$curdir
bmp_dir="${curdir}/bitmaps"

SCREEN_WIDTH=1920
PADDING='  '

while read -r line ; do
	case $line in
		S*)
			ssid=`iwgetid -r`
			sc=`iwconfig wlp3s0 | sed 's/  /\n/g' | grep Quality | sed 's/Link Quality://' | sed 's/Link Quality=//' | sed 's/ //g' | cut -d "/" -f 1`
			st=`iwconfig wlp3s0 | sed 's/  /\n/g' | grep Quality | sed 's/Link Quality://' | sed 's/Link Quality=//' | sed 's/ //g' | cut -d "/" -f 2`
			if [ -z "$ssid" ] ; then
				wico="${bmp_dir}/wifi_0.xbm"
			else
				wico=$(${panel_dir}/wifi_xbm_for_perc.py $sc $st )
				wico="${bmp_dir}/${wico}"
			fi
			ba=`acpi | cut -d ',' -f 2 | awk '{key=$0; getline; print key "" $0;}' | cut -d ' ' -f 2 | cut -d '%' -f 1`
			bb=`acpi | cut -d ',' -f 2 | awk '{key=$0; getline; print key "" $0;}' | cut -d ' ' -f 3 | cut -d '%' -f 1`

			bab=$(${panel_dir}/bat_xbm_for_perc.py $ba )
			bica="${bmp_dir}/${bab}"

			bbb=$(${panel_dir}/bat_xbm_for_perc.py $bb )
			bicb="${bmp_dir}/${bbb}"

			used_mem=`free -m | grep Mem | awk '{print $3}'`
			tot_mem=`free -m | grep Mem | awk '{print $2}'`

			# Not super exact but not an issue
			perc_mem=$((100*$used_mem/$tot_mem))

			SEP="^fg($COLOR_C)^fg($COLOR_C)"

			sys_infos="^fg($COLOR_D)^fg($COLOR_STATUS_FG)^bg($COLOR_D) RAM: ${perc_mem}% ^ca()^fg($COLOR_C)^fg($COLOR_STATUS_FG)^bg($COLOR_C)^ca(1,~/.config/bspwm/panel/popup_batt.sh) Batt: ^i(${bica})^i(${bicb}) ^ca()^fg($COLOR_B)^fg($COLOR_STATUS_FG)^bg($COLOR_B) Wifi: ^i(${wico})^ca() ^fg($COLOR_A)^fg($COLOR_STATUS_FG)^bg($COLOR_A) ^ca(1,~/.config/bspwm/panel/popup_cal.sh)${line#?} (${left})${PADDING}^ca()"
			;;
		T*)
			# xtitle output
			title="^bg($COLOR_TITLE_BG)${PADDING}^fg($COLOR_TITLE_FG)${line#?}${PADDING}^fg()^bg()"
			;;
		W*)
			# bspwm internal state
			wm_infos="^bg($COLOR_B)^fg($COLOR_BACKGROUND)^bg($COLOR_B)$PADDING"
			IFS=':'
			set -- ${line#?}
			while [ $# -gt 0 ] ; do
				item=$1
				case $item in
					[OoFfUu]*)
						# desktops
						name=${item#?}
						case $item in
							O*)
								# focused occupied desktop
								FG=$COLOR_STATUS_FG
								# BG=$COLOR_FOCUSED_OCCUPIED_BG
								ICO="●"
								;;
							F*)
								# focused free desktop
								FG=$COLOR_STATUS_FG
								ICO="○"
								# BG=$COLOR_FOCUSED_FREE_BG
								;;
							U*)
								# focused urgent desktop
								# FG=$COLOR_FOCUSED_URGENT_FG
								BG=$COLOR_STATUS_FG
								ICO="○"
								;;
							o*)
								# occupied desktop
								FG=$COLOR_D
								BG=$COLOR_OCCUPIED_BG
								ICO="●"
								;;
							f*)
								# free desktop
								FG=$COLOR_D
								BG=$COLOR_FREE_BG
								ICO="○"
								;;
							u*)
								# urgent desktop
								FG=$COLOR_D
								BG=$COLOR_URGENT_BG
								ICO="○"
								;;
						esac
						wm_infos="${wm_infos}^fg(${FG})^ca(1, bspc desktop -f ${name})^ca(2, bspc window -d ${name}) ${ICO} ^ca()^ca()"
						;;
					L*)
						# layout
						layout=$(printf "%s" "${item#?}" | sed 's/^\(.\).*/\U\1/')
						# ^ca(1, bspc desktop -l next)${PADDING}$layout${PADDING}^ca()
						wm_infos="${wm_infos}${PADDING}^fg($COLOR_BACKGROUND)^fg()^bg()${PADDING}${PADDING}^fg($COLOR_LAYOUT_FG)^bg($COLOR_LAYOUT_BG)"
						;;
				esac
				shift
			done
			;;
	esac
	left_side=$title
	printf "%s\n" "^fg($COLOR_DECOR)^fg($COLOR_TITLE_FG)^pa(0)$left_side^pa(850)$wm_infos^pa(1600)$sys_infos"
done

