#! /bin/sh

# Fontawesome icons
# Need the font from AUR
bspc monitor -d      


# Visual options
bspc config border_width        0
bspc config window_gap          2
bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config focus_follows_pointer true

# Colors
bspc config normal_border_color "#332d29"
bspc config active_border_color "#817267"
bspc config focused_border_color "#504339"
bspc config presel_border_color "#9a875f"
bspc config urgent_border_color "#9f7155"
bspc config focused_locked_border_color "#9a875f"

# Rules
bspc rule -a skype pseudo_tiled=on desktop=^3
bspc rule -a Transmission-gtk pseudo_tiled=on desktop=^7
bspc rule -a firefox desktop=^1
bspc rule -a google-chrome-stable desktop=^1

# Exec
compton &
~/.config/bspwm/panel/panel &
