#! /bin/sh

# Fontawesome icons
# Need the font from AUR
bspc monitor -d      


# Visual options
bspc config border_width        0
bspc config window_gap          2
bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config focus_follows_pointer true

# Colors
bspc config normal_border_color '#282828'
bspc config focused_border_color '#d5c4a1'
bspc config presel_border_color '#d79921'
bspc config normal_sticky_border_color '#1d2021'
bspc config focused_sticky_border_color '#d5c4a1'
bspc config urgent_border_color '#cc241d'

# Rules
bspc rule -a Skype desktop='^3' state=pseudo_tiled
bspc rule -a Transmission-gtk desktop='^7' state=pseudo_tiled
bspc rule -a Firefox desktop='^1'
bspc rule -a google-chrome desktop='^1'

# Exec
compton &
~/.config/bspwm/panel/panel &
